### ISSUE TITLE
Registro de Proveedores-BACK

### ISSUE THREAD

**Issue by rodrigo-hp** [casgroup-dev/users#14]
- [x] Hacer que el esquema de compañías soporte múltiples rubros
- [x] Añadir nuevos campos (ver issue relacionado en front)
- [x] Modificar funciones del archivo ./controllers/companies/crud/index.js para que coincida con el nuevo esquema
- [x] Escribir o modificar los tests relacionados

Link a Issue de FRONT relacionado: https://github.com/casgroup-dev/BFF/issues/1

**Comment by SetaSouto** [comment]
Actualizado los campos nuevos, pasando todos los test. Se cerrará cuando se haga el pull request.

**Comment by SetaSouto** [comment]
Ahora los *shadow users* tienen un token cuando consultan por si existen y con ese token pueden crear compañías.
